### ISSUE TITLE
As a Masspay User, I want bad monetary input to be ignored in the total

### ISSUE THREAD

**Issue by sddaniels** [niclake/DwollaExercise#2]
![screen shot 2019-02-14 at 11 22 14 am](https://user-images.githubusercontent.com/1263925/52804867-e6d5df80-304a-11e9-87b2-a7681749f552.png)

Desired behavior:
If there are any invalid amounts in rows, please ignore them when displaying the total. For example, if there is `badinput` in one row and `5.00` in another, the total should read `$5.00`. Please display `$0.00` instead of `$nnn.nn` if the total of all good input is zero.

Please add a unit test to cover this case.

**Comment by niclake** [comment]
- Fixed so bad inputs do not update totals.
- Fixed so $0 displays as $0.00.

Unit test not implemented. Will open new issue to address these.
